(require 'stark-semantic)
(require 'stark-cc-mode)
(require 'stark-markdown-mode)
(require 'stark-yaml-mode)
(require 'stark-web-development)
(require 'stark-web-development-kbd)
(require 'stark-python-mode)
(require 'stark-ruby-mode)

(provide 'stark-module-init)
